// Copyright 2017 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Generated by tools/bigint-tester.py.
var data = [{
  a: -0xe813d76adc0a177778c0c232c595e8572b783210f4a7009d7c1780,
  b: 0x0,
  r: -0x3a04f5dab70285ddde30308cb1657a15cade0c843d29c0275f05e1c000000000000000000000000000000000000000
}, {
  a: -0xded00dff14550,
  b: 0xd0,
  r: -0x1bda01bfe28aa98000000000000000000000000000000000000000000000000000000
}, {
  a: -0x50c2df089209be37998c8f6e30c4c95a61e77a9240,
  b: 0x40,
  r: -0x1430b7c224826f8de66323db8c3132569879dea490400000000000000000
}, {
  a: 0x668086293eab52b52b879f00375d0f513f1ff9a93df788e38520,
  b: -0x0,
  r: 0
}, {
  a: 0,
  b: -0x0,
  r: 0
}, {
  a: 0x26bd28fb3e06bb0d0,
  b: -0,
  r: 0x26bd28fb3e06bb0
}, {
  a: -0xa04dca5c74bdb1dbf2f0,
  b: -0x0,
  r: -0
}, {
  a: -0xd6b46ec3ead311e2e45ca4ae8aa9cf5acf4c2d6c61de06e9e30,
  b: -0,
  r: -0x35ad1bb0fab4c478b917292ba2aa73d6b3d30b5b187781ba0
}, {
  a: -0x1f19220,
  b: -0x0,
  r: -0x0
}, {
  a: 0x40,
  b: -0x0,
  r: 0x10
}, {
  a: -0xf60,
  b: 0x0,
  r: -0x3d900000000000000000000000000000000
}, {
  a: -0x70,
  b: -0x80,
  r: -0x0
}, {
  a: -0xa03bc462b00e4113a2472eb70,
  b: 0,
  r: -0
}, {
  a: 0x3816aa0f01396f4abe0ee7164e211ce60ce590b615d86f6e6363c0bdd513d8a0,
  b: 0x0,
  r: 0x3816aa0f01396f4abe0ee7164e211ce60ce590b615d86f6e6363c0bdd513d8a00
}, {
  a: -0xaf8711d29fdecd42a255f14aafe13b9404cced5df0af8b86080af7682c0,
  b: 0x0,
  r: -0
}, {
  a: 0x218b110,
  b: 0,
  r: 0
}, {
  a: 0x263fcb4707e6fd4a21b1f646ddd90a5e78d781c272621dcaf861d6250d7be675e060,
  b: -0x860,
  r: 0
}, {
  a: 0x8312b459b585847680,
  b: 0x0,
  r: 0x20c4ad166d61611da0b80000000000000000000
}, {
  a: 0xb45d42e0595a4b104b0b9a177ffdc52b401b61659fe163e720621aef8c8e6191ba0,
  b: 0x0,
  r: 0x5a2ea1702cad25882585cd0bbffee295a00db0b2cff0b1f390310d77c64730c8dd3d0
}, {
  a: -0x42d2c0,
  b: 0x0,
  r: -0x85a588000000000000000000000000000000000000000000000000000000000000000
}];
var error_count = 0;

for (var i = 0; i < data.length; i++) {
  var d = data[i];
  var r = d.a << d.b;

  if (d.r !== r) {
    print("Input A:  " + d.a.toString(16));
    print("Input B:  " + d.b.toString(16));
    print("Result:   " + r.toString(16));
    print("Expected: " + d.r);
    print("Op: <<");
    error_count++;
  }
}

if (error_count !== 0) {
  print("Finished with " + error_count + " errors.");
  quit(1);
}
