// Copyright 2017 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Generated by tools/bigint-tester.py.
var data = [{
  a: 0xc4fd438551d580,
  b: 0x91b42ee55a50d970,
  r: -0
}, {
  a: -0x86b766ec276e390087458ce093b07b2574732d5f3f5120,
  b: 0x4b1fe0dd23316de1b38b343d4112fbd7e8c8d081de5dbabda7357fd9e8684666930,
  r: -0x4b1fe0dd23316de1b38b34c3f879e7ff5701d10923ea9b5157b0a54e5b95a5a5e500
}, {
  a: 0x63e1eac0d5470c8f802ec390b6415c43ed16d28d0,
  b: -0xbe26927b2f6ae85b5d3062d869d22da005805d23142a236955127b6ca688c00,
  r: 0
}, {
  a: -0x873cf988993d97e5180,
  b: -0xd791aa365f881a7f05f21f73ef390c0b37408dd0a908801682464178420,
  r: 0
}, {
  a: -0xcb273d5b123eff101c62f016ae2896223b93b9114e40d0,
  b: 0x2169f8c954623f8381bf12fd0927e1a645f5b3c6c00e58105c297ba40446200,
  r: -0
}, {
  a: -0xe965bf745fffcf20,
  b: 0x7c3b92f8a030cbfca7cc5f2fd454459c79a3ac22015244680,
  r: -0
}, {
  a: 0,
  b: 0x6975a8ededffd265f472e660e10,
  r: -0x6975a8ededffd265f472e660e10
}, {
  a: -0x236bda1a3a9635190f26c3739b7342f33a27cd2560,
  b: 0x1a7e0,
  r: -0
}, {
  a: 0xb682b9c88f0b6d7b5e9a4f77dd0d7885d62cd162783b2e55b30b954e10caf0,
  b: 0x2c6574161d9aff7bbebd95e561fbd5d70d893e8c9772bcc697c0,
  r: 0xb682b9c88c451639fcc09f8021219f27800d140507629a6ce9946981a74e10
}, {
  a: 0xdd6aa5240c0,
  b: 0xb9c7bef20c0cc0f814cce3c40d43e4c20,
  r: -0
}, {
  a: 0x35cd14329d5f810,
  b: 0x25997b1f3500f9b27f2ce0,
  r: -0x25997b1bd82fb688a934d0
}, {
  a: -0x55ec15d7ed316df3fc7bcfcce0f0a6d7034113bad6d74bae88d4aab03030,
  b: 0x9d09b8869aab44d6690fad48c8dffd0e18cc21fb26c2a80ac08fd4f42296f46d37c0,
  r: -0x9d09b886a00a0633e7e2c42808a7ba0ae6db2c6896f6b9466dfd49af0b243f183ad0
}, {
  a: 0,
  b: -0xfbf3b308a6066d497e0,
  r: 0
}, {
  a: 0x6acfc1e4b681be9582cd28453387ed2c29f5eb4cd6d78aaac60,
  b: -0x4f5990,
  r: 0
}, {
  a: -0xc93eb5cae0c90eb77e702ccb44eea6180829d0b360870,
  b: 0,
  r: -0
}, {
  a: -0x324ef140a16c5c20a9a189a720136f4836ea98050,
  b: 0x49471582a658bf5524128e130b3378d29331baa8eb0,
  r: -0x49796473e6fa2bb144bc2f9cb2538c41db68a540f0
}, {
  a: 0x6f15ac8490de4e308286fdde1142ad0052c0,
  b: 0x9ca6c715de18d7f64a751452e967b5807eec951777245ce5fe0,
  r: -0x9ca6c715de18d78734c88fc20b1984fdf7eeb70634775c933b0
}, {
  a: -0xc3030,
  b: 0x5ec0a706a54978a59b10007942e563957ad22e708678fbfdb02862b2c0,
  r: -0x5ec0a706a54978a59b10007942e563957ad22e708678fbfdb02925b670
}, {
  a: -0xdb736b5f3979c24f70aafa5f17711d725d552a9778e0,
  b: 0x70b56a0773498a45b796cf79ea18211610,
  r: -0
}, {
  a: 0xe91b9a797168c6b7440f940,
  b: -0x2588c1301521dd9646a2e22e3aca462ca95e76069be2f7b95d8bb810,
  r: 0x2588c1301521dd9646a2e22e3aca462caa4791a11554608014cfc7b10
}];
var error_count = 0;

for (var i = 0; i < data.length; i++) {
  var d = data[i];
  var r = d.a - d.b;

  if (d.r !== r) {
    print("Input A:  " + d.a.toString(16));
    print("Input B:  " + d.b.toString(16));
    print("Result:   " + r.toString(16));
    print("Expected: " + d.r);
    print("Op: -");
    error_count++;
  }
}

if (error_count !== 0) {
  print("Finished with " + error_count + " errors.");
  quit(1);
}
